apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ include "my-java-app.fullname" . }}
 labels:
  {{- include "my-java-app.labels" . | nindent 4 }}
spec:
 replicas: {{ .Values.replicaCount }}
 selector:
 matchLabels:
  app: {{ include "my-java-app.name" . }}
 template:
 metadata:
  labels:
   app: {{ include "my-java-app.name" . }}
 spec:
   containers:
   - name: {{ .Chart.Name }}
   image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
   ports:
   - containerPort: {{ .Values.service.targetPort }}
